version: "2"
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    # command: bash -c “npm run seedDB & npm run start”
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"


# version: “2”
# services:
#   web:
#     image: aizamjj/reservation-form_web:firsttry
#     command: bash -c “npm run seedDB & npm start”
#     ports:
#       - “80:8080”
#     depends_on:
#       - mongo
#   mongo:
#     image: mongo
#     ports:
#       - “27017:27017"